```{r}
library(tidyverse)
```

```{r}
vaccines <- read.csv(
    "https://data.chhs.ca.gov/dataset/e283ee5a-cf18-4f20-a92c-ee94a2866ccd/resource/130d7ba2-b6eb-438d-a412-741bde207e1c/download/covid19vaccinesbycounty.csv"
) %>%
    filter(county == "Santa Barbara") %>%
    mutate(date = as.Date(administered_date, "%Y-%m-%d")) %>%
    filter(date < as.Date("2021-7-1")) %>%
    select(
        date,
        full=cumulative_fully_vaccinated,
        single=cumulative_at_least_one_dose,
        partial=total_partially_vaccinated # its just full - single
    ) 

vaccines %>%
    arrange(desc(partial))

vaccines %>%
    mutate(full = full + partial) %>%
    gather("type", "n", -date) %>%
ggplot(aes(x=date, y=n, group=type)) +
    geom_line(aes(color=type))
```

```{r}
pop <- read.csv("https://data.chhs.ca.gov/dataset/f333528b-4d38-4814-bebb-12db1f10f535/resource/046cdd2b-31e5-4d34-9ed3-b48cdbc4be7a/download/covid19cases_test.csv") %>%
    filter(area == "Santa Barbara") %>%
    select(date, population) %>%
    mutate(date = as.Date(date, "%Y-%m-%d"))

# same throughout
unique(pop$population)

vaccines %>%
    group_by(type) %>%
    summarise(pct = last(n) / last(pop$population)) 

vaccines
```

```{r}
left_join(vaccines, pop, by="date") %>%
    mutate(
        singlePct = single / population,
        fullPct = full / population,
        partialPct = partial / population
    ) %>%
    select(date, fullPct, singlePct, partialPct) %>%
    write.csv("county_vaccines.csv", row.names=FALSE)
```

```{r}
variants <- read.csv("variant_googlesheets.csv")

library(lubridate)
library(tidyverse)


variants %>% summarise(count = sum(count))


var <- variants %>%
    filter(variant != "no_interest") %>%
    spread(variant, count) %>%
    mutate(date = as.Date(date, "%m/%d/%Y"))

var <- var[order(as.Date(var$date, "%m/%d/%Y")),]

variants%>%
    filter(variant != "no_interest") %>%
    summarise(count = sum(count))

write.csv(var, "variants.csv", na="0", row.names=F)
```


```{r}
x <- c(729, 772, 797, 815, 854, 894, 902, 938, 949, 953)
y <- c(1031, 1060, 1096, 1153, 1191, 1232, 1265, 1303, 1326, 1394)

summary(lm(y~x))




qchisq(0.9, 6)


library(tidyverse)

data.frame(
    male=c(270, 259, 147),
    female=c(148, 139, 79)
) %>%
    chisq.test()

data.frame(a=c(158, 172, 167, 172, 161), b=c(215, 192, 212, 205, 199, 215, 200))

anova(c(158, 172, 167, 172, 161), c(215, 192, 212, 205, 199, 215, 200))

var(c(158, 172, 167, 172, 161))/var(c(215, 192, 212, 205, 199, 215, 200))


qf(0.975, 6, 4)



a=c(91, 101, 110, 121, 125)
b=c(91, 146, 176, 179, 278)
c=c(79, 86, 124, 141, 141)

chisq.test(c(108, 113, 105, 111, 123, 104, 119))


qchisq(0.99, 2)


ftest <- var.test( c(215, 192, 212, 205, 199, 215, 200),c(158, 172, 167, 172, 161), alternative = "two.sided")

ftest

chisq.test(c(108, 112, 105, 112, 121, 104, 119))


qchisq(0.95, 2)


data.frame(
    male=c(273, 256, 151),
    female=c(144, 138, 79)
) %>%
    chisq.test()

var.test(c(213, 195, 208, 210, 199, 214, 199), c(159, 174, 167, 172, 163), alternative="two.sided")

# difference of means
a <- c(89, 100, 109, 121, 125)
b <- c(90, 145, 173, 178, 277)
c <- c(80, 84, 124, 141, 141)

# DO IT ON THE CALCULATOR
qf(0.99, 2, 15-3)

qf(0.99, 2, 15-3)
```

```{r}
qchisq(0.9, 6)

chisq.test(c(109, 111, 104, 112, 120, 104, 125))


m <- matrix(c(21, 30, 15, 20, 19, 16, 41, 20), nrow=2, byrow=T)

apply(m, c(1,2), sum)

sum(m)


qf(0.975, 6, 4)

var.test(c(214, 190, 210, 208, 196, 215, 199), c(155, 172, 168, 171, 161), alternative="two.sided")
```

